name: Deploy to Server

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/sample-service-restart/
            git pull origin main # Pull the latest changes into the bare repo
            cp index.html /var/www/html/
            /bin/bash post-receive
